name: Test Node.js App

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Building the image from the Dockerfile
      uses: ./.github/worflows
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 19

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test